# Generated by Django 3.1.7 on 2023-02-11 23:33

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20230212_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[300, 300], upload_to='posts'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profil_picture',
            field=django_resized.forms.ResizedImageField(crop=None, default='C:\\Users\\so16s\\PycharmProjects\\social_network\\src\\mediafiles/profil_pictures/profil_picture_default.png', force_format=None, keep_meta=True, max_length=300, quality=-1, scale=None, size=[300, 300], upload_to='profil_pictures'),
        ),
    ]
