# Generated by Django 3.1.7 on 2023-02-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20230212_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profil_picture',
            field=models.ImageField(default='C:\\Users\\so16s\\PycharmProjects\\social_network\\src\\mediafiles/profil_pictures/profil_picture_default.png', max_length=300, upload_to='profil_pictures'),
        ),
    ]
